extend the liveness probe with a swisssearch request
geoadmin/service-sphinxsearch pull request #532
Opened 2022-09-14 06:35 UTC by ltclm

searchd status can be ok before the swisssearch requests are working 504 errors are responded at that momennt. it takes a moment before the swisssearch requests are served correctly.

with this extension the container won't be tagged healthy before swisssearch requests are working

2022-09-14 06:57 UTC, hansmannj approved these changes
Thanks! :+1:

2022-09-14 08:19 UTC, rebert approved these changes
lgtm - if an empty answer of siwsssearch_status will exit 0 as well

2022-09-14 08:21 UTC, ltclm commented
> lgtm - if an empty answer of siwsssearch_status will exit 0 as well

yes exit status is 0 if the index exist and is accessible / usable.

2022-09-14 11:27 UTC, ltclm commented
@ltshb i think it makes more sense to do this test in the wsgi app.

The 503 errors are already covered by the healtcheck at container level.
The 504 errors are mostly because of the wsgi_timeout of 3s between wsgi and sphinxsearch. I think if we want to get rid of them, we have to add this test to the /checker/ready endpoint in the wsgi app instead.

the first requests on heavy indexes like swisssearch are slow right after the index rotation. they can take more than 3s generating 504 errors.

2022-09-15 05:41 UTC, ltshb requested changes
From my understanding this will make it worse, marking the container unhealthy just because an index is not yet ready will cause a container restart !
The questions are the following:
1. How long takes a swisssearch query in the beginning ? 
2. Is this time always for the first swisssearch query or just if the first query is done just after a restart ? I mean if we restart wait let say 2-3 hour and do the first swisssearch query, is the query also slow ?

I mean if it takes just a bit longer than 3 seconds (e.g. 4-5 seconds) then we need to increase the WSGI timeout. If it takes more that than (e.g. 10-30 seconds) we need to find a better way. One idea would be to use the sphinx API to do a basic swisssearch query as readiness probe in the wsgi app, removing the whole file readiness probe stuff which would be simpler.

2022-09-15 06:06 UTC, ltclm commented
@ltshb thats true, it is better to increase the wsgi timeout instead or add a swisssearch request to the wsgi liveness probe.
the first queries after a rotation can take up to 5-10s. as far as i can say this initial slow phase takes about 60s.

but maybe we should first check the access logs and see how many 504 errors we really have.

2022-09-15 06:06 UTC, closed without merging