BGDIDIC-2472: update zone index
geoadmin/service-sphinxsearch pull request #543
Opened 2022-11-21 14:29 UTC by faselm

2022-11-21 14:38 UTC, ltclm requested changes

2022-11-21 14:38 UTC, ltclm commented on conf/uvek.conf.part
> +source src_ch_bazl_einschraenkungen_drohnen_zone_name : def_searchable_features
to be consistent with the other indexes, please use the layer name as source.
`src_ch_bazl_einschraenkungen_drohnen`

2022-11-22 09:24 UTC, faselm commented
Can I merge it too?

2022-11-22 09:38 UTC, ltclm approved these changes

2022-11-22 10:19 UTC, merged