BGDIDIC-997: add new fields
geoadmin/service-sphinxsearch pull request #563
Opened 2023-03-28 14:14 UTC by faselm

2023-03-28 15:29 UTC, ltclm approved these changes

2023-03-28 15:29 UTC, ltclm commented on conf/stopo.conf.part
> +            , remove_accents(concat_ws(' ', COALESCE(name, ''), fm_at_td, purpose, discover)) as detail \
the coalesce could be removed.

2023-03-28 15:30 UTC, ltclm requested changes

2023-03-29 06:56 UTC, faselm commented
Thanks, I added the lang suffix, it's good now

2023-03-29 07:03 UTC, ltclm approved these changes

2023-04-12 08:43 UTC, merged